version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    restart: always
    container_name: messanger-api
    volumes:
      - .:/app
    ports:
      - "8009:8000"
    networks:
      - messanger_net

  db:
    image: postgres:15.2
    container_name: messanger-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5430:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    networks:
      - messanger_net

  telegram_bot:
    build: .
    volumes:
      - .:/app
    entrypoint: python bot.py
    restart: always
    container_name: notifications-bot
    env_file:
      - .env
    networks:
      - messanger_net

  redis:
    image: redis:latest
    container_name: messanger_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - messanger_net

  celery:
    restart: unless-stopped
    container_name: messanger_celery
    build: .
    env_file:
      - .env
    depends_on:
      - api
      - redis
    command: celery -A src.celery_tasks.celery:celery_app worker --loglevel=info
    networks:
      - messanger_net


networks:
  messanger_net:
    external:
      name: messanger_net
